# Generated by Django 5.0.1 on 2024-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.BinaryField(),
        ),
    ]
